name: CI

on:
  push:
  pull_request:
  schedule:
  - cron: "0 0 * * *" # Run every day at midnight

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: fedora:latest

    steps:
    - uses: actions/checkout@v2

    - name: Run nightly check
      env:
          COPR_CONFIG_CONTENT: ${{ secrets.COPR_CONFIG_CONTENT }}
      run: |
        yum install -y fedora-packager copr-cli
        mkdir $HOME/.config
        echo "$COPR_CONFIG_CONTENT" > $HOME/.config/copr
        ./virt-preview
